# Generated by Django 5.0.6 on 2024-05-31 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_application_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='educational_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.educational_institution', verbose_name='Образовательное учреждение'),
        ),
    ]
