# Generated by Django 5.0.6 on 2024-05-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_educational_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='level_of_education',
            field=models.CharField(choices=[('СПО', 'СПО'), ('Бакалавриат', 'Бакалавриат'), ('Магистратура', 'Магистратура'), ('Специалитет', 'Специалитет')], default='Бакалавриат', max_length=30, verbose_name='Уровень образования'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level_of_education',
            field=models.CharField(choices=[('СПО', 'СПО'), ('Бакалавриат', 'Бакалавриат'), ('Магистратура', 'Магистратура'), ('Специалитет', 'Специалитет')], default='Бакалавриат', max_length=30, verbose_name='Уровень образования'),
        ),
    ]
