# Generated by Django 5.0.6 on 2024-06-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Принят', 'Принят'), ('Обрабатывается', 'Обрабатывается'), ('Отказ', 'Отказ')], default='Обрабатывается', max_length=40, verbose_name='Статус'),
        ),
    ]
