# Generated by Django 5.0.6 on 2024-06-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_of_appointment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата приема'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='position',
            field=models.CharField(choices=[('Глава приема', 'Глава приема'), ('Падаван', 'Падаван')], max_length=100, verbose_name='Должность'),
        ),
    ]
