# Generated by Django 5.0.6 on 2024-06-16 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.profession', verbose_name='Специальность'),
        ),
    ]
